import type { Metadata } from "next";
import { ThemeProvider } from "@/libs/contexts/providers/theme-provider.tsx";
import "./globals.css";
import { ReactQueryProvider } from "@/libs/contexts/providers/react-query-provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ReactQueryProvider>
              <Toaster position="top-right" richColors />
              {children}
            </ReactQueryProvider>
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}